### PR TITLE
update dependencies to latest

### PR DESCRIPTION
**Pull request by tobert**

### CODE REVIEW

**Review by adammohammed — COMMENTED** [review]
Can you also bump the go version in the mod file? This doesn't build on 1.18 it seems.
```bash
[nix-shell:~/repos/otel-init-go]$ go version
go version go1.18.10 linux/amd64

[nix-shell:~/repos/otel-init-go]$ go build ./...
# go.opentelemetry.io/otel/sdk/trace
../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/provider.go:78:24: undefined: atomic.Pointer
../../go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/provider.go:80:20: undefined: atomic.Bool
note: module requires Go 1.19
```

**Review by adammohammed — APPROVED** [review]

**Review by adammohammed — APPROVED** [review]
